### ISSUE TITLE
Server title doesn't have enough padding when it's wrapped

### ISSUE THREAD

**Issue by jaigak** [BreeceW/Oxidized#104]
![image](https://user-images.githubusercontent.com/45227503/126260479-c0f92c3a-ede4-4f26-bbfe-5828aad01337.png)

In this case, it shouldn't wrap because there's more space on the right to show it without being wrapped to the next line.

**Comment by jaigak** [comment]
Seems like the official Discord client uses ellipses instead of wrapping the title.

**Comment by BreeceW** [comment]
Change made in 1.12.0
