### ISSUE TITLE
Rename the copy text option to copy message text and copy link to copy message link

### ISSUE THREAD

**Issue by jaigak** [BreeceW/Oxidized#106]
The copy text and copy link options are misleading. For clarity, I recommend renaming 'copy text' to 'copy message text' and 'copy link'.

**Comment by BreeceW** [comment]
![Menu flyout with Copy text and Copy message link options](https://user-images.githubusercontent.com/18747724/151783604-119ac278-3c54-4c34-b0de-885016b1f84b.png)
Copy link was confusing and now clarifies that it is for the link as of 1.12.11.
