### ISSUE TITLE
Send notification when replying to a message should be selected by default

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#11]

**Comment by BreeceW** [comment]
There are a few things I’d like to consider here:

- Should Show notification remember whether it is checked or not between replies to different messages?
- Should there be a setting for changing the default mode? And if so how would that impact the previous point? Could there be a triple-state option? Such as “Send notification by default“ or “Don’t send notification by default” or “Remember last used”
- If that option is implemented, what should the default be? I would like to survey users before changing it.

**Comment by MarcAnt01** [comment]
I actually would like notifications to be selected by default, since it's what happens with the default clients.
I think having an option is not a good idea, if you still want to keep a different behavior (which I don't like actually) just memorize the option.

**Comment by BreeceW** [comment]
This doesn’t change the fact that there might need to be an option, but I do want to point out that you can more easily check Send notification with the shortcut Alt+N.

**Comment by MarcAnt01** [comment]
> This doesn’t change the fact that there might need to be an option, but I do want to point out that you can more easily check Send notification with the shortcut Alt+N.

I started using Oxidized more frequently now and it's too annoying to have to select "send notification" every time. Can you just make an option and move it out of the reply panel?

**Comment by BreeceW** [comment]
Changes made in 1.9.0
Combo box with options for don’t send notifications by default, do send notifications by default, and remember last setting used.
Default is still don’t send notifications by default.
