### ISSUE TITLE
Feature request: The hamburger menu should automatically close when the window is too small

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#112]
**Description of feature or change**
When the window is getting smaller, the chat should be totally visible while the hamburger menu hidden

**Mockup**
It should close and look like that automatically
![image](https://user-images.githubusercontent.com/43090263/127334177-b5cf17c7-9ac0-4428-8654-49c6a51d4299.png)

**Rationale**
This improves usability with a small window, since having to close the hamburger menu every time is a bad ux and not expected from a user viewpoint.

**Comment by BreeceW** [comment]
I agree. I’ll get this in the next Oxidized Valley preview.

**Comment by BreeceW** [comment]
This is implemented in Oxidized Valley 0.0.4.
