### ISSUE TITLE
Support sharing to multiple channels at once

### ISSUE THREAD

**Issue by jaigak** [BreeceW/Oxidized#115]
Today when you share to Oxidized, it only lets you send it to a single channel however sometimes you may need to send the same thing to multiple channels (eg: Feedback Hub links) and currently you'd need to share it one channel first, then copy and paste to other channels. Consider providing the ability to share to multiple channels at once so don't need to copy and paste.

**Comment by BreeceW** [comment]
No. No batch operations will be supported.
