### ISSUE TITLE
Feature request: people without a propic should have colored clyde instead of an empty circle

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#125]
**Description of feature or change**
Atm if a person does not have a propic, it looks very weird. My idea is to add clyde mascotte there.

**Rationale**
All the other Discord apps have this and adding it would create consistency. I don't have any other ideas of what could be used instead, but leaving an empty circle isn't a good idea for me.

**Comment by BreeceW** [comment]
The “robot face design” you speak of is a registered trademark of Discord Inc. We have no right to use it in this app. You can propose another solution for users who do not have an avatar set, or I will close this issue.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/132104987-8d656b04-9fd3-4410-99f1-1035b8f44d81.png)
For people without a username I wouldn't show at all the profile picture here keeping just the roles. For the name in the chat. What are your thoughts about an initial of their name colored the same with the role like Telegram does for example? For reference
![image](https://user-images.githubusercontent.com/43090263/132105083-0f092841-2b25-4388-97ee-9054a38381fa.png)

**Comment by BreeceW** [comment]
I was considering the `PersonPicture` control. I will keep in mind your suggestion to color the blank icon the same as the username. That sounds useful.

**Comment by xmine64** [comment]
Same on servers that don't have an icon or picture

Oxidized:
![image](https://user-images.githubusercontent.com/21140798/145758987-681973a0-ae0e-4a1e-a912-f3ca9947f094.png)

Discord:
![image](https://user-images.githubusercontent.com/21140798/145759055-3bcb0a9a-b369-411f-8edf-8397fb3bb936.png)

**Comment by BreeceW** [comment]
Oxidized Valley is now using initials instead of empty circles.
