### ISSUE TITLE
Profile pop-up of people in a server doesn't work if a person has no roles

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#13]
![image](https://user-images.githubusercontent.com/43090263/102898554-fa81d680-4469-11eb-8997-49d3aa911259.png)

**Comment by BreeceW** [comment]
Can you elaborate? I have just tested this and see no problem.
Maybe I am misunderstanding, since it seems to me that the flyout in your photo does have roles in it.

**Comment by MarcAnt01** [comment]
If a person doesn't have any roles, that kind of pop-up doesn't appear. Anyway, after some testing it seems to happen just some times, maybe it is worthy to investigate

**Comment by BreeceW** [comment]
Sometimes the flyout does not appear, but I don’t think it’s correlated to there being roles or not.

**Comment by BreeceW** [comment]
I haven’t seen this issue in a long time, so I’m going to close it now. If you still have problems, feel free to elaborate and re-open this issue.
