### ISSUE TITLE
Bug: "Suppress All Role @mentions" option not respected

### ISSUE THREAD

**Issue by yoshiask** [BreeceW/Oxidized#132]
**Describe the bug**
In official Discord clients, there is a server notification option to suppress all role mentions. Oxidized doesn't recognize this option, so pings from muted and suppressed servers are still shown.

**To Reproduce**
1. Suppress all role mentions from a guild
2. Open Oxidized
3. Have your role pinged in said guild
4. Observe that the mention shows as a ping in Oxidized, but not in official Discord clients.

**System(s) that problem occurred on**
Windows 10 21H2, Windows 10 Mobile FCU
PC/Mobile
x64/ARM

**Comment by BreeceW** [comment]
When you reload the app, do the mentions still show up?

**Comment by yoshiask** [comment]
Yes.

**Comment by BreeceW** [comment]
Note: the mentions do not persist across reloads

**Comment by BreeceW** [comment]
This feature will be added in Oxidized Valley 0.0.12.

**Comment by BreeceW** [comment]
This is now implemented in Oxidized Valley 0.0.12.
