### ISSUE TITLE
Bug: Sign-in page doesn't open on W10M Anymore

### ISSUE THREAD

**Issue by burd1** [BreeceW/Oxidized#135]
Today i got logged out of Oxidized and its valley counterpart and upon attempting to relogin i get a white screen, absolutely nothing happens and i cant login as i cant put in my details. The same seems to be happening on Unicord aswell. Seems to be an issue with discord.com/login i'm not sure if anything can be done to fix it.
I'm using an HP Elite x3 with Windows 10 Mobile 1709 15254. I have tried on both WiFi and Cellular data. The page seems to be opening fine on Windows 7, Linux and Windows 10 Desktop.
![oxidized](https://user-images.githubusercontent.com/5015897/187602340-c2c57c4b-0634-43f3-9d5e-bd5c3512ee46.jpg)

**Comment by BreeceW** [comment]
You can use an alternative log in option by right-clicking (or tapping and holding) the log in button on the welcome screen.

**Comment by burd1** [comment]
> You can use an alternative log in option by right-clicking (or tapping and holding) the log in button on the welcome screen.

Getting the token is a difficult task and annoying too, but i suppose its better than nothing. Thank you.

**Comment by BreeceW** [comment]
Web-based login is restored in Oxidized 1.12.18 and Oxidized Valley 0.0.9.

**Comment by mediaexplorer74** [comment]
> Web-based login is restored in Oxidized 1.12.18 and Oxidized Valley 0.0.9.

Cool. You're very progressive c# dev. Please decide to share your coding expiriences if you can...
