### ISSUE TITLE
Tooltip on server emojis list is connected to the icon instead of the button containing it

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#17]
If I put the mouse hover out of the icon area, but within the buttons it won't show the tooltip

**Comment by BreeceW** [comment]
Could you try again? I can’t reproduce this, and the tooltip is not associated with the icon but rather the outer container, which should span the whole area of the button.

**Comment by BreeceW** [comment]
I understand now—yes, this can be fixed.

**Comment by BreeceW** [comment]
![Tooltip shows wherever on the button](https://user-images.githubusercontent.com/18747724/125225853-f39fa180-e29d-11eb-8625-a4a963c47ae0.png)
This has been fixed and will be included in the next update.

**Comment by BreeceW** [comment]
Fixed in 1.12.0
