### ISSUE TITLE
Top panel icons disappear when resizing oxidized window horizontally (over a certain point)

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#18]
![image](https://user-images.githubusercontent.com/43090263/102899884-e048f800-446b-11eb-9fd4-90a4ea6cda3f.png)

**Comment by BreeceW** [comment]
I do not believe that they disappear, rather they are moved to the side. When the app gets resized past a certain point, the side panel turns into a tray menu that slides open and closed with the button that appears in the top left corner. This is done to work on cell phones and compact overlay.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/102900910-3d917900-446d-11eb-8f00-73562e36a96f.png)

**Comment by BreeceW** [comment]
Yes, that is how it is supposed to look. Click the button on the top left corner and you will see the those buttons on the top right corner.
