### ISSUE TITLE
Implement a proper dark theme

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#20]
Currently there's a black amoled theme, but I find it really annoying, since all the apps/sites that I use have just a dark mode. Black amoled theme could be kept as an option, but I think the default one should be dark.

**Comment by BreeceW** [comment]
From my point of view, the theme with a black background is the dark mode, and this is the case with many of the apps that ship with Windows, though newer apps seem to be headed towards dark gray. I am willing to add an option for a - gray theme.

- The light theme is also completely white. Should it be light gray?
- Could it be like Office, which has various shades available?

**Comment by MarcAnt01** [comment]
> From my point of view, the theme with a black background is the dark mode, and this is the case with many of the apps that ship with Windows, though newer apps seem to be headed towards dark gray. I am willing to add an option for a gray theme.
> 
> * The light theme is also completely white. Should it be light gray?
> * Could it be like Office, which has various shades available?

I would just opt out the amoled color for something like dark grey, I think white is ok for light theme, but black is not for the dark one

**Comment by BreeceW** [comment]
Updated in 1.7.0
There is now a light and dark gray theme, with a toggle for “black/white” mode in settings. The gray themes are default on all devices except mobile, which remains black/white by default.
The light gray theme uses pure white for the main body. The white light theme has been updated to be completely white (previously, the app used light gray on panes, which is now what the light gray theme is).

**Comment by BreeceW** [comment]
I’ve closed this issue because I believe the changes in 1.7.0 ameliorate the concerns in this issue. Feel free to re-open it if you have additional feedback.
