### ISSUE TITLE
Feature request: Hiding muted channels

### ISSUE THREAD

**Issue by FireCubeStudios** [BreeceW/Oxidized#26]
The main discord client has ability to hide muted channels. The option can be toggled with a checkmark when right clicking server icon so oxidized can do something similair but a menutoggleflyoutitem could be fine too.

Uses of feature: hides uneeded channels, customizability to server and oxidized will be a step closer to being on par with discord client

**Comment by BreeceW** [comment]
This feature is likely finished and will almost certainly available in the next update.
![image](https://user-images.githubusercontent.com/18747724/104118219-5915d400-52f5-11eb-963d-885166278e0e.png)

**Comment by BreeceW** [comment]
Fixed in 1.7.0
