### ISSUE TITLE
Feature Request: Quick switch feature from the official Discord app

### ISSUE THREAD

**Issue by KibSquib48** [BreeceW/Oxidized#41]
Basically, I want something like this where you can search for servers and automatically jump to them with a keyboard shortcut like Ctrl + K
![image](https://user-images.githubusercontent.com/33189136/106409885-9b6f9400-640f-11eb-8e6a-748b3902f638.png)

also if I could use the forward and back buttons on my mouse to navigate my channel history that would be cool too

**Comment by BreeceW** [comment]
This is planned.
Forward and back navigation is worthy of its own issue. See #82.

**Comment by BreeceW** [comment]
This feature will be in 1.11.0. It looks like this:
![The new quick switcher is a search box with a list of channels below it](https://user-images.githubusercontent.com/18747724/118316266-9c12ce80-b4c4-11eb-8c97-9a1724202a2f.png)

**Comment by BreeceW** [comment]
Added in 1.11.0
