### ISSUE TITLE
Bug: Multiple Oxidized media sessions

### ISSUE THREAD

**Issue by KibSquib48** [BreeceW/Oxidized#48]
Every time I open Oxidized and play a video or music file I get about 5 media sessions in ModernFlyouts, and it's the same without ModernFlyouts running so it seems to be an Oxidized problem

Edit: This seems to be because of how videos are loaded, and before you actually start playing a video, the media session for it is loaded. This isn't that much of a problem, until you finish watching a video and the session is still there, and then you go to another chat, and then the videos from there show up too, and it piles up until it's basically impossible to find anything that isn't from Oxidized in the volume flyout

**Comment by winston-de** [comment]
Yeah I've been noticing this as well. 
I don't know if this helps, but I ran into a similar issue a while back when using the MediaPlayerElement control and was able to fix it by handling the ``MediaPlayerElement.Unloaded`` event and setting then manually setting the Source property to null.

**Comment by BreeceW** [comment]
```csharp
private void Video_Unloaded(object sender, RoutedEventArgs e)
{
    ((MediaPlayerElement)sender).Source = null;
    // ...
}
```
Thanks for the tip, @winston-de. Unfortunately, this is what we’ve been doing for quite some time already and that presumably does not resolve this issue.

**Comment by BreeceW** [comment]
Disposing the media source first and then setting it to null unloads the video from the system media transport controls. Thanks to @ahmed605 for the advice in fixing this.

```csharp
private void Video_Unloaded(object sender, RoutedEventArgs e)
{
    var mpe = (MediaPlayerElement)sender;
    if (mpe.Source is IDisposable ms)
    {
        ms.Dispose();
    }
    mpe.Source = null;
}
```
