### ISSUE TITLE
Click on a mention should show the flyout of the mentioned person

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#55]

**Comment by BreeceW** [comment]
Clicking a mention is planned to show this flyout
![image](https://user-images.githubusercontent.com/18747724/107399062-4c3ff800-6ace-11eb-9d71-95273c156fd5.png)
rather than the profile that I believe you were alluding to in #52

**Comment by MarcAnt01** [comment]
Yes, I meant that flyout sorry for the confusion

**Comment by BreeceW** [comment]
Added in 1.12.0
