### ISSUE TITLE
Use the new WinUI ProgressRing

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#59]

**Comment by BreeceW** [comment]
This will likely be done with our pivot to Sun Valley, once that comes around.

**Comment by BreeceW** [comment]
![WinUI progress ring on reconnecting screen](https://user-images.githubusercontent.com/18747724/137302738-a387482d-16f5-4540-ad1a-9e378a6fff0f.gif)
I have added the new progress rings and progress bars. They will come with the rest of the visual updates.

**Comment by BreeceW** [comment]
The new progress controls are used in Oxidized Valley.
