### ISSUE TITLE
Cannot paste a picture in the typing bar without the keyboard shortcut

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#71]
I usually do ctrl + v, but if the keyboard is not attached I might want just to long press on the typing bar and paste, but that's not possible currently. I know I could work that around using the expanded keyboard, but I'd rather have an option to paste like in basically every app
Example
![image](https://user-images.githubusercontent.com/43090263/113353976-be9abf00-933e-11eb-922b-1548f67475f6.png)

**Comment by BreeceW** [comment]
Closed for not following issue template.
