### ISSUE TITLE
Less invasive use of multi-windowing

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#8]
Currently multi-windowing with uwp apps has a big limitations, if you close the main window you cannot go back to it through secondary windows. I expect the photo viewer to open within the same window

**Comment by BreeceW** [comment]
I agree. The photo viewer as well as the settings should open in the same window so as to be consistent with virtually all the UWP apps out there.

**Comment by BreeceW** [comment]
This raises some questions for the settings page:
* Should the settings page take over the whole window, where you would have to click a back button to return to the main app?
* Should the settings page be a flyout, akin to how it worked in the old Microsoft Edge? (I don’t particularly like this)
* Should the settings page cover only a part of the app, and if so, which part?

**Comment by MarcAnt01** [comment]
I think the setting pay should cover everything

**Comment by BreeceW** [comment]
New options in 1.9.0 allow these pop ups to open in the same window or another window. Is this design sufficient to close this issue?
