### ISSUE TITLE
Feature request: Allow to copy pictures directly from the chat view

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#86]
**Description of feature or change**
Like it's possible to copy text, it makes sense to add the possibility to copy a picture without opening it

**Mockup**
Horrible, but that's all I can give you
![image](https://user-images.githubusercontent.com/43090263/118291796-43e5c780-b4d8-11eb-8218-c8972ea0e921.png)

**Rationale**
When copying multiple pictures, it's annoying to have to open the picture and then copy it every time

**Comment by BreeceW** [comment]
https://user-images.githubusercontent.com/18747724/118311559-10963f00-b4be-11eb-9407-411356783e99.mp4

This is what I’ve come up with. Let me know what you think.

**Comment by BreeceW** [comment]
![New image context menu on a card](https://user-images.githubusercontent.com/18747724/118313278-87ccd280-b4c0-11eb-9856-f57d89d65138.png)
I’ve made it work for images embedded on cards too.

**Comment by MarcAnt01** [comment]
Perfect, thanks

**Comment by BreeceW** [comment]
Added in 1.11.0
