### ISSUE TITLE
Feature request: Ask for confirmation before entering a voice channel

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#93]
**Description of feature or change**
Add an optional banner that warns the user before joining a voice channel

**Mockup**
I don't have any particular mockup to show, but a simple contentdialog, with join, undo etc. would be appropriate

**Rationale**
I often join audio channels by mistake especially in big servers, this would prevent it. Unfortunately Discord itself doesn't have this feature.

**Comment by BreeceW** [comment]
Option (enabled by default) added in 1.12.0

**Comment by Crare** [comment]
> Option (enabled by default) added in 1.12.0

Where is it? I don't see that option anywhere. There's way too many settings to find this. I don't see it in the Desktop app nor in the browser web app.
