### ISSUE TITLE
Bug: Oxidized ignores max file size for servers/dms

### ISSUE THREAD

**Issue by MarcAnt01** [BreeceW/Oxidized#97]
**Describe the bug**
Oxidized ignores max file size for servers/dms

**To Reproduce**
1. Send a file bigger than limit size;
2. Nothing will be displayed, but the file won't have been sent.

**System(s) that problem occurred on**
Windows 10 21H1

**Comment by BreeceW** [comment]
This is fixed in Oxidized Valley.
